pre_install() {
    ln -sf /usr/share/zoneinfo/Europe/Brussels /etc/localtime
    hwclock --systohc

    timedatectl set-ntp true
}

post_install() {
    mkinitcpio -p linux

    post_upgrade
}

post_upgrade() {
    cp etc/hosts etc/hosts.pacsave
    cp etc/locale.conf etc/locale.conf.pacsave
    cp etc/locale.gen etc/locale.gen.pacsave
    mv etc/hosts.pacnew etc/hosts
    mv etc/locale.conf.pacnew etc/locale.conf
    mv etc/locale.gen.pacnew etc/locale.gen

    locale-gen
}
