HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt autocd
setopt correct

zstyle ":completion:*" menu select
zstyle ":completion:*" matcher-list "m:{a-zA-Z-_}={A-Za-z_-}" "r:|=*" "l:|=* r:|=*"

zmodload zsh/complist

bindkey -e
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward
bindkey "^[[5~" up-line-or-history
bindkey "^[[6~" down-line-or-history
bindkey -M menuselect "^[[A" vi-up-line-or-history
bindkey -M menuselect "^[[B" vi-down-line-or-history
bindkey -M menuselect "^[[C" vi-forward-char
bindkey -M menuselect "^[[D" vi-backward-char

autoload -Uz compinit; compinit
autoload -U promptinit; promptinit

prompt pure

alias ls="ls --color=auto"
alias s="sudo"
alias serve="python -m http.server"
